### ISSUE TITLE
API Services are open and not secured

### ISSUE THREAD

**Issue by jersonjohn** [codingfreak/blogsamples#1]
Right now the API.Services are not secured ,  can access user records without any authentication via services.  How can I make that secured,  Also do you know how can I achieve all these Registration/Login/etc via Web api services and consume that in my angularapp.  Is it some thing easily done from this existing project?  Thanks in advance

**Comment by codingfreak** [comment]
Closing this because it is pretty outdated now and I can't cover this issue now. Sorry.
