### ISSUE TITLE
UserId not found error

### ISSUE THREAD

**Issue by kwizu** [codingfreak/blogsamples#2]
I obtain the following error, what am i missing?

Server Error in '/' Application.

UserId not found.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: UserId not found.

Source Error: 

Line 20:         {
Line 21:             // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
Line 22:             var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
Line 23:             // Add custom user claims here
Line 24:             return userIdentity;

**Comment by codingfreak** [comment]
I can't reproduce this and it is pretty outdated now. Sorry for not answering sooner.
